name: Release

on: 
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version number
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}
      - name: Tidy
        run: |
          mkdir dist
          mv -v ${{ github.event.repository.name }} dist
          rm -fr dist/${{ github.event.repository.name }}/.git dist/${{ github.event.repository.name }}/.github
      - name: Compress
        uses: papeloto/action-zip@v1
        with:
          files: dist
          dest: ${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip
